new endpoint for tfg 2425 signos
agarsev/visse-app pull request #2
Opened 2024-11-14 08:32 UTC by sandra-conde-gonzalez

New endpoint '/recognize/tfg-2425-signos' for post method returns all logo information needed for tfg-2425-signos.

2024-11-27 18:05 UTC, agarsev requested changes
Buen trabajo. Voy probándolo mientras hacéis el cambio menor que comento.

2024-11-27 18:05 UTC, agarsev commented on backend/main.py
> +@app.post("/recognize/tfg-2425-signos", response_model=Response)
En lugar de `/recognize/tfg-2425-signos`, mejor una URL más genérica, que pueda servir a más gente en el futuro. Quizá `/recognize/raw`, o `/detect`, o algo similar.

2024-11-27 20:05 UTC, sandra-conde-gonzalez commented on backend/main.py
> +@app.post("/recognize/tfg-2425-signos", response_model=Response)
Ya hemos cambiado la URL a /recognize/raw. Si hay algo más que modificar nos dices.

2024-12-14 18:39 UTC, agarsev approved these changes

2024-12-14 18:43 UTC, merged